### ISSUE TITLE
Unnecessarily complicated label for user override

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/theme-manager-plugin#13]
Label in Theme Manager 0.1:

> Disable user theme override

This is worded unnecessarily complicated. How about:

> Do not allow users to select a different theme

Ideally the checkbox would be inverted, and checked by default, so it could be

> Allow users to select a different theme

**Comment by timja** [comment]
I initially had that but was having issues getting both the UI and jcasc to default to enabled

But sure makes sense

**Comment by daniel-beck** [comment]
Right, but even if not inverted to be a positive statement, it can be rephrased to be clearer.

**Comment by timja** [comment]
https://github.com/jenkinsci/theme-manager-plugin/pull/16
