### ISSUE TITLE
User preferences do not work

### ISSUE THREAD

**Issue by fqueiruga** [jenkinsci/theme-manager-plugin#21]
I've just updated to 0.2 and the user settings do not work. Global config is always observed. Maybe it has to do with some of this prs? 

- https://github.com/jenkinsci/theme-manager-plugin/pull/11
- https://github.com/jenkinsci/theme-manager-plugin/pull/15

**Comment by timja** [comment]
on it

**Comment by timja** [comment]
Released in https://github.com/jenkinsci/theme-manager-plugin/releases/tag/theme-manager-0.3
