### ISSUE TITLE
Add new Material theme to the plugin listing

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/theme-manager-plugin#32]
I saw this plugin on Friday, and it solved an issue I have been struggling with for a while - how to provide user themes.

I have added a new repo which is an attempt to port the material theme to this plugin.
https://github.com/timbrown5/jenkins-material-theme-plugin

There are probably a lot of fixes required, but it seems to work from my initial testing.
(Although as I am posting this I realise I already need to change the package name (as I use io.jenkins.plugins).

**Comment by timja** [comment]
Nice, we can add the theme here once it’s hosted by the Jenkins project and the first version has been released

**Comment by timbrown5** [comment]
> Nice, we can add the theme here once it’s hosted by the Jenkins project and the first version has been released
Cool. I will try to get to that point (not done it before, so will try and follow your guide 👍).

**Comment by timbrown5** [comment]
I have raised a PR, so closing this issue.
