### ISSUE TITLE
Theme stopped workin after recent update due to Mixed Conten

### ISSUE THREAD

**Issue by artkrz** [jenkinsci/theme-manager-plugin#44]
```
Mixed Content: The page at 'https://jenkins.foo.bar/' was loaded over HTTPS,
but requested an insecure stylesheet 'http://jenkins.foo.bar/theme-dark/theme.css'.
This request has been blocked; the content must be served over HTTPS.
```

I'm not sure when this happened, was it due to Jenkins or Dark Theme update but it just stopped working. My setup is AWS NLB with TLS listener terminating SSL that redirects traffic to (HTTP) Nginx with following configuration:

```
upstream jenkins {
  server 127.0.0.1:8080 fail_timeout=0;
}

server {
  listen 80;
  server_name jenkins.foo.bar;

  location / {
    proxy_set_header        Host $host:$server_port;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_redirect http:// https://;
    proxy_pass              http://jenkins;
    # Required for new HTTP-based CLI
    proxy_http_version 1.1;
    proxy_request_buffering off;
    proxy_buffering off; # Required for HTTP-based CLI to work over SSL
    # workaround for https://issues.jenkins-ci.org/browse/JENKINS-45651
    add_header 'X-SSH-Endpoint' 'jenkins.foo.bar:50022' always;
  }
}
```

I'm 100% sure this was working and I haven't changed anything in the configuration since, just kept Jenkins and all plugins (including dark theme) up to date. I have *Jenkins URL* set to `https://jenkins.foo.bar`

I would assume is a configuration problem but as I wrote, it was working fine for a while and just stopped recently.

**Comment by timja** [comment]
the block of the config you showed appears to be only for port 80 unless I'm misunderstanding? what's your port 443 config like?

**Comment by artkrz** [comment]
There's no configuration for 443. I have AWS Network Load Balancer in front of it that terminates TLS. Pretty common deployment scenario.

**Comment by timja** [comment]
why do you need nginx in front of Jenkins then?

**Comment by artkrz** [comment]
Hardcoding result:

```GET https://jenkins.inf.filestack.org:80/theme-dark/theme.css net::ERR_CONNECTION_TIMED_OUT```

Why NLB? We use AWS issued certificates, You cannot export these. NLB does not set any headers, as far as I remember it's not possible as it's TCP load balancer.

**Comment by timja** [comment]
Add `proxy_set_header X-Forwarded-Port 443`

**Comment by artkrz** [comment]
Doesn't work, it adds port but leaves http:

```
http://jenkins.foo.bar:443/theme-dark/theme.css
```

**Comment by timja** [comment]
have you also set `proxy_set_header X-Forwarded-Proto https;`?

can you paste your current config if still an issue after above

**Comment by artkrz** [comment]
No I did not. It was set to `$scheme`, I did now and it works! Thank You, here;s the working config:

```
upstream jenkins {
  server 127.0.0.1:8080 fail_timeout=0;
}

server {
  listen 80;
  server_name jenkins.foo.bar;

  location / {
    proxy_set_header        Host $host:$server_port;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto https;
    proxy_set_header        X-Forwarded-Port 443;
    proxy_redirect          http:// https://;
    proxy_pass              http://jenkins;
    # Required for new HTTP-based CLI
    proxy_http_version      1.1;
    proxy_request_buffering off;
    proxy_buffering         off; # Required for HTTP-based CLI to work over SSL
    # workaround for https://issues.jenkins-ci.org/browse/JENKINS-45651
    add_header              'X-SSH-Endpoint' 'jenkins.foo.bar:50022' always;
  }
}
```

**Comment by timja** [comment]
Basically your Jenkins thought it was running on http because the `Forwarded` headers weren't being set properly.

From a quick google it should be possible for them to be set properly but without knowing exactly what you're using and some time to play around I don't know why it didn't work out of the box for you.

I would have expected your Jenkins to be complaining about it as well with something like:

![image](https://user-images.githubusercontent.com/21194782/108175989-529b2900-70f9-11eb-9f6f-aebea778c794.png)

Which links to:
https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-troubleshooting/
