### ISSUE TITLE
Themes are not loaded on HTTPS webservers due to mixed content blocking

### ISSUE THREAD

**Issue by iridinite** [jenkinsci/theme-manager-plugin#55]
### Version report

Jenkins and plugins versions report:

- Jenkins version 2.291 running on Linux (latest Raspbian Buster)
- [Plugin list on Gist, because it's long](https://gist.github.com/iridinite/482f841d1327b305e1ffcf62374612a2)

### Reproduction steps

- Run Jenkins through a HTTPS-enabled webserver. In my case, I'm using Apache as public-facing webserver (which adds the HTTPS layer) as a reverse-proxy to the Jenkins instance on the local network.
- Install Theme Manager and a theme (I'm using [Material theme](https://plugins.jenkins.io/material-theme/))
- Load any Jenkins page.
- Observe that the installed theme does not appear.

### Results

The selected theme is not displayed because the `<link>` element generated by the plugin uses a http:// protocol prefix instead of the expected https://. This causes browsers (e.g. Firefox 88) to treat the link as mixed content and block it.

Example:

The following line appears in loaded Jenkins pages:

```
<link type="text/css" rel="stylesheet" href="http://example.com/jenkins/theme-material-indigo/theme-indigo.css">
```

which yields the following warning in the Firefox developer console:

```
Blocked loading mixed active content “http://example.com/jenkins/theme-material-indigo/theme-indigo.css”
```

The plugin should either 
- emit a stylesheet link that uses the proper protocol, using the "Jenkins URL" global system setting (Manage Jenkins > Configure System > Jenkins Location > Jenkins URL), which will have been configured by the administrator to use the correct protocol & publicly visible path.
- leave off the domain part of the stylesheet link entirely, and instead emit e.g. `/jenkins/theme-material-indigo/theme-indigo.css`, which allows the browser to do the resolving itself.

**Comment by timja** [comment]
This means your reverse proxy is mis-configured

see https://github.com/jenkinsci/theme-manager-plugin/issues/44

**Comment by iridinite** [comment]
Oops 😄 Looks like you're right; I had set up everything _except_ the XFP header. Works now, cheers!

For any future readers: the easiest fix is adding the following to your Apache config for the site / virtual host:
```
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
```
