### ISSUE TITLE
Convert to the Incubated project before the release?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/theme-manager-plugin#6]
Hi @timja ,

I would suggest to make it an incubated project so that we have more freedom w.r.t next steps (e.g. merging it into the Jenkins core). I would suggest the following stapes:

* Add "Incubated project" to the description and docs, similar to https://plugins.jenkins.io/pipeline-as-yaml/
* Mark all APIs with `@Restricted(Beta.class)`

**Comment by timja** [comment]
Sure
