### ISSUE TITLE
Add Neo2 theme to the listing

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/theme-manager-plugin#9]
It would be great to add the Neo2 Theme to the listing of themes in the plugin. Even if it is behind the current Jenkins core requirements and needs some patches, it would be great to offer it in the list

References:

* https://tobix.github.io/jenkins-neo2-theme/

**Comment by timja** [comment]
cc @TobiX if you're interested to create a plugin for this

https://github.com/jenkinsci/theme-manager-plugin/blob/master/docs/developer-guide.md

**Comment by timja** [comment]
Fixed by https://github.com/jenkinsci/theme-manager-plugin/pull/34
